parameters:
    # Adds a fallback DATABASE_URL if the env var is not set. This allows you
    # to run cache:warmup even if your environment variables are not available
    # yet. You should not need to change this value.
    #env(DATABASE_URL): 'mysql://$_ENV['DB_USER']:$_ENV['DB_PASSWORD']@$_ENV['DB_HOST']:$_ENV['DB_PORT']/$_ENV['DB_NAME']'

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        url: '%env(DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Guestbook:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Piv\Guestbook\Entity'
                alias: Guestbook
