security:
    providers:
        users:
            entity:
                class: 'Piv\Guestbook\Entity\User'
    encoders:
        Piv\Guestbook\Entity\User:
            algorithm: auto
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login
                failure_path: login_failure_route_name
                use_referer: true
                always_use_default_target_path: true
                default_target_path: after_login_route_name
                target_path_parameter: go_to
                failure_path_parameter: back_to
            guard:
                authenticators:
                     - Piv\Guestbook\Security\LoginFormAuthenticator
