index:
    path:     /{sortflag}/{count}
    controller: Piv\Guestbook\Controller\UserController::show
    defaults:
        sortflag: 'ByDateDesc'
        count: '1'
    requirements:
      sortflag: '(ByUsername|ByEmail|ByDate)(Asc|Desc)'
      count:    \d+
login:
    path:  /login
    controller: Piv\Guestbook\Controller\SecurityController::login
logout:
    path: /logout
    controller: Piv\Guestbook\Controller\SecurityController::logout
admin:
    path: /admin/{sortflag}/{count}
    controller: Piv\Guestbook\Controller\AdminController::adminDashboard
    defaults:
        sortflag: 'ByDateDesc'
        count: '1'
    requirements:
      sortflag: '(ByUsername|ByEmail|ByDate)(Asc|Desc)'
      count:    \d+
admin-action:
    path: /admin/action
    controller: Piv\Guestbook\Controller\AdminController::adminAction
