indexRoute:
    path:     /
    controller: Piv\Guestbook\Controller\UserController::show

sortingRoute:
    path:     /{sortflag}/{count}
    defaults: { controller: 'Piv\Guestbook\Controller\UserController::show' }
    requirements:
      sortflag: '(ByName|ByEmail|ByDate)(Asc|Desc)'
      count:    \d+
