indexRoute:
    path:     /
    defaults: { controller: 'Piv\Guestbook\Src\Controllers\GuestbookController::show' }

indexRoute1:
    path:     /foo/{col}
    defaults: { controller: 'Piv\Guestbook\Src\Controllers\GuestbookController::show' }

sortingRoute:
    path:     /{sortflag}/{count}
    defaults: { controller: 'Piv\Guestbook\Src\Controllers\GuestbookController::show' }
    requirements:
      sortflag: '(ByName|ByEmail|ByDate)(Asc|Desc)'
      count:    \d+
