parameters:
    locale: 'ru'
    translation.fileTranslation: 'messages.ru.yaml'
    translation.type: 'yaml'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    Piv\Guestbook\:
        resource: '../src/*'
        exclude: '../src/{entity,helpers,migrations,Kernel.php}'
    Piv\Guestbook\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    Piv\Guestbook\Twig\TwigFilterExtension:
        tags: [twig.extension]
    Piv\Guestbook\Twig\TwigFunctionExtension:
        tags: [twig.extension]
providers:
        users:
            entity:
                # the class of the entity that represents users
                class: 'Piv\Guestbook\Entity\User'
                # the property to query by - e.g. username, email, etc
                property: 'name'
