parameters:
    form.factory: form
    form.validator: validator
    twig: twig
    homepage.numberMessages: 25

services:
    form.factory:
        class:     Symfony\Component\Form\FormFactory
        arguments: ['%form.factory%']
    validator:
        class:     Symfony\Component\Validator\Validator\ValidatorInterface
        arguments: ['%mailer.transport%']
    twig:
        class:     Twig\Environment
        calls:
            - [setMailer, ['@mailer']]
